// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Permission struct {
	ID   int16  `json:"id"`
	Name string `json:"name"`
}

type RefreshToken struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
	Revoked   bool      `json:"revoked"`
}

type Role struct {
	ID   int16  `json:"id"`
	Name string `json:"name"`
}

type RolePermission struct {
	RoleID       int16 `json:"role_id"`
	PermissionID int16 `json:"permission_id"`
}

type User struct {
	ID           uuid.UUID    `json:"id"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

type UserRole struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID int16     `json:"role_id"`
}
