// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles_and_permissions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const assignRoleToEntity = `-- name: AssignRoleToEntity :exec
INSERT INTO user_roles (user_id, role_id)
SELECT $1,
 id
FROM roles
WHERE name = $2
`

type AssignRoleToEntityParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) AssignRoleToEntity(ctx context.Context, arg AssignRoleToEntityParams) error {
	_, err := q.db.ExecContext(ctx, assignRoleToEntity, arg.UserID, arg.Name)
	return err
}

const getEntityRoles = `-- name: GetEntityRoles :many
SELECT r.name
FROM user_roles ur
 JOIN roles r ON r.id = ur.role_id
WHERE ur.user_id = $1
`

func (q *Queries) GetEntityRoles(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getEntityRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntityRolesPermissions = `-- name: GetEntityRolesPermissions :many
SELECT DISTINCT p.name
FROM user_roles ur
 JOIN role_permissions rp ON rp.role_id = ur.role_id
 JOIN permissions p ON p.id = rp.permission_id
WHERE ur.user_id = $1
`

func (q *Queries) GetEntityRolesPermissions(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getEntityRolesPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissions = `-- name: GetPermissions :many
SELECT id, name
FROM permissions
`

func (q *Queries) GetPermissions(ctx context.Context) ([]*Permission, error) {
	rows, err := q.db.QueryContext(ctx, getPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRolePermissions = `-- name: GetRolePermissions :many
SELECT p.name
FROM role_permissions rp
 JOIN permissions p ON p.id = rp.permission_id
WHERE rp.role_id = $1
`

func (q *Queries) GetRolePermissions(ctx context.Context, roleID int16) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRolePermissionsByRoleName = `-- name: GetRolePermissionsByRoleName :many
SELECT p.name
FROM roles r
 JOIN role_permissions rp ON rp.role_id = r.id
 JOIN permissions p ON p.id = rp.permission_id
WHERE r.name = $1
`

func (q *Queries) GetRolePermissionsByRoleName(ctx context.Context, name string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getRolePermissionsByRoleName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoles = `-- name: GetRoles :many
SELECT id, name
FROM roles
`

func (q *Queries) GetRoles(ctx context.Context) ([]*Role, error) {
	rows, err := q.db.QueryContext(ctx, getRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllEntityRoles = `-- name: RemoveAllEntityRoles :exec
DELETE FROM user_roles
WHERE user_id = $1
`

func (q *Queries) RemoveAllEntityRoles(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removeAllEntityRoles, userID)
	return err
}

const revokeRoleFromEntity = `-- name: RevokeRoleFromEntity :exec
DELETE FROM user_roles
WHERE user_id = $1
 AND role_id = (
  SELECT id
  FROM roles
  WHERE name = $2
 )
`

type RevokeRoleFromEntityParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) RevokeRoleFromEntity(ctx context.Context, arg RevokeRoleFromEntityParams) error {
	_, err := q.db.ExecContext(ctx, revokeRoleFromEntity, arg.UserID, arg.Name)
	return err
}
